# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
#
# Install git hooks
#   pre-commit install
# Update this file:
#   pre-commit autoupdate
# Apply to all files without committing:
#   pre-commit run --all-files
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      # - id: terraform_validate # this downloads ALL modules locally and takes too long
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
