# velero helm values
# source (with full comments): https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

# https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/releases
initContainers:
  - name: velero-plugin-for-microsoft-azure
    # https://hub.docker.com/r/velero/velero-plugin-for-microsoft-azure/tags
    image: velero/velero-plugin-for-microsoft-azure:v1.6.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

# BackupStorageLocation and VolumeSnapshotLocation
configuration:
  backupStorageLocation:
    - name: default
      bucket: velero
      default: true
      provider: azure
      credential:
        name: velero-credentials
        key: cloud
  volumeSnapshotLocation:
    - name: default
      provider: azure

credentials:
  useSecret: true
  existingSecret: velero-credentials
